version: '2'

services:
    web:
        container_name: ${APP_NAME}_web
        build: ./web
        environment:
             - APACHE_RUN_USER=#1000
        volumes:
             - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
        ports:
             - 8080:80
        working_dir: ${APP_PATH_CONTAINER}
             
    db:
        container_name: ${APP_NAME}_db
        image: mariadb
        restart: always
        environment:
           MYSQL_ROOT_PASSWORD: root
        volumes:
            - ${DB_PATH_HOST}:/var/lib/mysql    

    adminer:
        container_name: ${APP_NAME}_adminer
        image: adminer
        restart: always
        ports:
           - 6080:8080           

    search:
       container_name: ${APP_NAME}_search
       image: elasticsearch:6.8.13
       ports:
           - 6200:9200

    composer:
        image: composer:1.6
        volumes:
            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
        working_dir: ${APP_PATH_CONTAINER}    
        command: composer install